routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'site', 'uses' => 'SiteController@index']);
Route::post('', ['as' => 'contact.send', 'uses' => 'SiteController@postContact']);

Route::get('/admin', 'Admin\AdminController@index')->name('dashboard');
Route::get('/admin/help', 'Admin\AdminController@help')->name('help');

Route::prefix('admin')->middleware('auth')->group(function () {
    Route::get('services/deleted', ['as' => 'services.deleted', 'uses' => 'Admin\ServiceController@deleted']);
    Route::put('services/{service}/recovery', ['as' => 'services.recovery', 'uses' => 'Admin\ServiceController@recovery']);
    Route::resource('services', 'Admin\ServiceController');

    Route::get('categories/{category}/products', ['as' => 'categories.products', 'uses' => 'Admin\CategoryController@showProducts']);
    Route::get('categories/deleted', ['as' => 'categories.deleted', 'uses' => 'Admin\CategoryController@deleted']);
    Route::put('categories/{category}/recovery', ['as' => 'categories.recovery', 'uses' => 'Admin\CategoryController@recovery']);
    Route::resource('categories', 'Admin\CategoryController');

    Route::get('products/deleted', ['as' => 'products.deleted', 'uses' => 'Admin\ProductController@deleted']);
    Route::put('products/{product}/recovery', ['as' => 'products.recovery', 'uses' => 'Admin\ProductController@recovery']);
    Route::resource('products', 'Admin\ProductController');

    Route::get('partners/deleted', ['as' => 'partners.deleted', 'uses' => 'Admin\PartnerController@deleted']);
    Route::put('partners/{partner}/recovery', ['as' => 'partners.recovery', 'uses' => 'Admin\PartnerController@recovery']);
    Route::resource('partners', 'Admin\PartnerController');
});

Route::post('/send', 'EmailController@send')->name('send');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable = [
        'image_id', 'name', 'deleted'
    ];

    public function image()
    {
        return $this->belongsTo('App\Image');
    }
}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Image;
use App\Service;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Intervention\Image\ImageManagerStatic;

class ServiceController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $request->user()->authorizeRole(['admin']);

        $services = Service::where('deleted', '=', 'N')->orderBy('id', 'DESC')->paginate(5);
        $breadcrumbs = [
            ['url' => route('dashboard'), 'title' => 'Dashboard'],
            ['url' => '', 'title' => 'Serviços']
        ];

        return view('admin.services.index', compact('services', 'breadcrumbs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $request->user()->authorizeRole(['admin']);

        $breadcrumbs = [
            ['url' => route('dashboard'), 'title' => 'Dashboard'],
            ['url' => route('services.index'), 'title' => 'Serviços'],
            ['url' => '', 'title' => 'Cadastrar']
        ];

        return view('admin.services.create', compact('breadcrumbs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->user()->authorizeRole(['admin']);

        $this->validate($request, [
            'name' => 'required',
            'image' => 'required|image'
        ]);

        if ($request->hasFile('image')) {
            $image = $request->image;
            $name = time() . '.' . $image->getClientOriginalExtension();
            $url = 'images/uploads/services/';

            $image->move($url, $name);

            $croppedImage = ImageManagerStatic::make($url . $name)->resize(77, 51)
                ->save($url . 'cropped' . $name);

            $imageModel = Image::create(['url' => $url . $name]);
            $imageModel->file()->create(['url' => $url . 'cropped' . $name, 'size' => 'service']);
            $imageModel->service()->create(['name' => $request->name]);
        }

        return redirect()->route('services.index')
            ->with('success', 'Serviço cadastrado com sucesso.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $request->user()->authorizeRole(['admin']);

        $service = Service::find($id);
        $breadcrumbs = [
            ['url' => route('dashboard'), 'title' => 'Dashboard'],
            ['url' => route('services.index'), 'title' => 'Serviços'],
            ['url' => '', 'title' => 'Atualizar']
        ];

        return view('admin.services.edit', compact('service', 'breadcrumbs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->user()->authorizeRole(['admin']);

        $this->validate($request, [
            'name' => 'required'
        ]);

        $service = Service::find($id);
        $service->update($request->all());

        if ($request->hasFile('image')) {
            $this->validate($request, [
                'image' => 'required|image'
            ]);

            $image = $request->image;
            $name = time() . '.' . $image->getClientOriginalExtension();
            $url = 'images/upload/services/';

            $image->move($url, $name);

            $croppedImage = ImageManagerStatic::make($url . $name)->resize(77, 51)
                ->save($url . 'cropped' . $name);

            $imageModel = Image::create(['url' => $url . $name]);
            $imageModel->file()->create(['url' => $url . 'cropped' . $name, 'size' => 'service']);

            $service->update(['image_id' => $imageModel->id]);
        }

        return redirect()->route('services.index')
            ->with('success', 'Serviço atualizado com sucesso.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $request->user()->authorizeRole(['admin']);

        Service::find($id)->update(['deleted' => 'Y']);

        return redirect()->route('services.index')
            ->with('success', 'Serviço deletado com sucesso.');
    }

     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function deleted(Request $request)
    {
        $request->user()->authorizeRole(['admin']);

        $services = Service::where('deleted', '=', 'Y')->orderBy('id', 'DESC')->paginate(5);
        $breadcrumbs = [
            ['url' => route('dashboard'), 'title' => 'Dashboard'],
            ['url' => route('services.index'), 'title' => 'Serviços'],
            ['url' => '', 'title' => 'Deletados']
        ];

        return view('admin.services.deleted', compact('services', 'breadcrumbs'));
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function recovery(Request $request, $id)
    {
        $request->user()->authorizeRole(['admin']);

        Service::find($id)->update(['deleted' => 'N']);

        return redirect()->route('services.deleted')
            ->with('success', 'Serviço recuperado com sucesso.');
    }
}

resources/views/admin/services/_form.blade.php
<div class="input-field">
    <input id="name" name="name" type="text" class="validate">
    <label for="name">Nome</label>
</div>

<div class="file-field input-field">
    <div class="btn">
        <span>Carregar Imagem</span>
        <input type="file" name="image">
    </div>
    <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
    </div>
</div>

resources/views/admin/services/create.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('admin.components.breadcrumbs')

    @if(count($errors) > 0)
        <div class="row">
            <div class="col s12">
                <div class="card red darken-2">
                    <div class="card-content white-text">
                        <span class="card-title">Erros</span>
                        @foreach($errors->all() as $message)
                            <li>{{ $message }}</li>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <form action="{{ route('services.store') }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            
            @include('admin.services._form')

            <a href="{{ route('services.index') }}" class="btn red">Cancelar</a>
            <button class="btn green right">Cadastrar</button>
        </form>
    </div>
@endsection

resources/views/admin/services/deleted.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('admin.components.breadcrumbs')

    @if(count($errors) > 0)
        <div class="row">
            <div class="col s12">
                <div class="card red darken-2">
                    <div class="card-content white-text">
                        <span class="card-title">Erros</span>
                        @foreach($errors->all() as $message)
                            <li>{{ $message }}</li>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <table>
            <thead>
                <td>#</td>
                <td>Nome</td>
                <td>Imagem</td>
                <td>Ação</td>
            </thead>
            <tbody>
                @foreach($services as $service)
                    <tr>
                        <td>{{ $service->id }}</td>
                        <td>{{ $service->name }}</td>
                        <td><img width="50" class="materialboxed" src="{{ $service->image->getUrl() }}"></td>
                        <td>
                            <form action="{{ route('services.recovery', $service->id) }}" method="post">
                                {{ method_field('PUT') }}
                                {{ csrf_field() }}

                                <button title="Recuperar" class="btn green">
                                    <i class="material-icons">restore</i>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="row">
        <a href="{{ route('services.index') }}" class="btn blue left">Voltar</a>
    </div>

    <div align="center" class="row">
        {{ $services->links() }}
    </div>
@endsection

resources/views/admin/services/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('admin.components.breadcrumbs')

    @if(count($errors) > 0)
        <div class="row">
            <div class="col s12">
                <div class="card red darken-2">
                    <div class="card-content white-text">
                        <span class="card-title">Erros</span>
                        @foreach($errors->all() as $message)
                            <li>{{ $message }}</li>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <form action="{{ route('services.update', $service->id) }}" method="post" enctype="multipart/form-data">
            {{ method_field('PUT') }}
            {{ csrf_field() }}

            <div class="input-field">
                <input id="name" name="name" type="text" class="validate"
                    value="{{ isset($service->name) ? $service->name : '' }}">
                <label for="name">Nome</label>
            </div>
            <div class="file-field input-field">
                <div class="btn">
                    <span>Carregar Imagem</span>
                    <input name="image" type="file">
                </div>
                <div class="file-path-wrapper">
                    <input type="text" class="file-path-wrapper">
                </div>
            </div>

            <a href="{{ route('services.index') }}" class="btn red">Cancelar</a>
            <button class="btn green right">Atualizar</button>
        </form>
    </div>
@endsection

resources/views/admin/services/index.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('admin.components.breadcrumbs')

    @if(count($errors) > 0)
        <div class="row">
            <div class="col s12">
                <div class="card red darken-2">
                    <div class="card-content white-text">
                        <span class="card-title">Erros</span>
                        @foreach($errors->all() as $message)
                            <li>{{ $message }}</li>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <table>
            <thead>
                <td>#</td>
                <td>Nome</td>
                <td>Imagem</td>
                <td>Ação</td>
            </thead>
            <tbody>
                @foreach($services as $service)
                    <tr>
                        <td>{{ $service->id }}</td>
                        <td>{{ $service->name }}</td>
                        <td><img width="50" class="materialboxed" src="{{ $service->image->getUrl() }}"></td>
                        <td>
                            <form action="{{ route('services.destroy', $service->id) }}" method="post">
                                <a title="Atualizar" href="{{ route('services.edit', $service->id) }}" class="btn orange">
                                    <i class="material-icons">mode_edit</i>
                                </a>

                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}

                                <button title="Deletar" class="btn red">
                                    <i class="material-icons">delete</i>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="row">
        <a href="{{ route('dashboard') }}" class="btn blue left">Voltar</a>
        <div class="right">
            <a href="{{ route('services.create') }}" class="btn green">Cadastrar</a>
            <a href="{{ route('services.deleted') }}" class="btn red">Deletados</a>
        </div>
    </div>

    <div align="center" class="row">
        {{ $services->links() }}
    </div>
@endsection