routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'site', 'uses' => 'SiteController@index']);
Route::post('', ['as' => 'contact.send', 'uses' => 'SiteController@postContact']);

Route::get('/admin', 'Admin\AdminController@index')->name('dashboard');
Route::get('/admin/help', 'Admin\AdminController@help')->name('help');

Route::prefix('admin')->middleware('auth')->group(function () {
    Route::get('services/deleted', ['as' => 'services.deleted', 'uses' => 'Admin\ServiceController@deleted']);
    Route::put('services/{service}/recovery', ['as' => 'services.recovery', 'uses' => 'Admin\ServiceController@recovery']);
    Route::resource('services', 'Admin\ServiceController');

    Route::get('categories/{category}/products', ['as' => 'categories.products', 'uses' => 'Admin\CategoryController@showProducts']);
    Route::get('categories/deleted', ['as' => 'categories.deleted', 'uses' => 'Admin\CategoryController@deleted']);
    Route::put('categories/{category}/recovery', ['as' => 'categories.recovery', 'uses' => 'Admin\CategoryController@recovery']);
    Route::resource('categories', 'Admin\CategoryController');

    Route::get('products/deleted', ['as' => 'products.deleted', 'uses' => 'Admin\ProductController@deleted']);
    Route::put('products/{product}/recovery', ['as' => 'products.recovery', 'uses' => 'Admin\ProductController@recovery']);
    Route::resource('products', 'Admin\ProductController');

    Route::get('partners/deleted', ['as' => 'partners.deleted', 'uses' => 'Admin\PartnerController@deleted']);
    Route::put('partners/{partner}/recovery', ['as' => 'partners.recovery', 'uses' => 'Admin\PartnerController@recovery']);
    Route::resource('partners', 'Admin\PartnerController');
});

Route::post('/send', 'EmailController@send')->name('send');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/dashboard.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('admin.components.breadcrumbs')

    <div class="row">
        <div class="col s6">
            <div class="card blue-grey darken-2">
                <div class="card-content white-text">
                    <span class="card-title">Serviços</span>
                    <p>Você tem {{ $serviceQty }} serviços cadastrados</p>
                </div>
                <div class="card-action">
                    <a href="{{ route('services.index') }}">Gerenciar</a>
                </div>
            </div>
        </div>

        <div class="col s6">
            <div class="card blue-grey darken-2">
                <div class="card-content white-text">
                    <span class="card-title">Categorias</span>
                    <p>Você tem {{ $categoryQty }} categorias cadastradas</p>
                </div>
                <div class="card-action">
                    <a href="{{ route('categories.index') }}">Gerenciar</a>
                </div>
            </div>
        </div>

        <div class="col s6">
            <div class="card blue-grey darken-2">
                <div class="card-content white-text">
                    <span class="card-title">Produtos</span>
                    <p>Você tem {{ $productQty }} produtos cadastrados</p>
                </div>
                <div class="card-action">
                    <a href="{{ route('products.index') }}">Gerenciar</a>
                </div>
            </div>
        </div>

        <div class="col s6">
            <div class="card blue-grey darken-2">
                <div class="card-content white-text">
                    <span class="card-title">Parceiros</span>
                    <p>Você tem {{ $partnerQty }} parceiros cadastrados</p>
                </div>
                <div class="card-action">
                    <a href="{{ route('partners.index') }}">Gerenciar</a>
                </div>
            </div>
        </div>

        <div class="col s6">
            <div class="card blue-grey darken-2">
                <div class="card-content white-text">
                    <span class="card-title">Visitas</span>
                    @if($visitQty > 0)
                        <p>Seu site tem {{ $visitQty }} visitas</p>
                    @else
                        <p>Seu site não tem nenhuma visita</p>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/help.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('admin.components.breadcrumbs')

    <ul class="collapsible" data-collapsible="accordion">
        <li>
            <div class="collapsible-header active"><i class="material-icons">dashboard</i>Dashboard</div>
            <div class="collapsible-body"><span>Nesta seção você tem uma lista dos recursos que podem ser gerenciados em seu site. O cartão "Visitas" informa o número de acessos ao seu site.</span></div>
        </li>
        <li>
            <div class="collapsible-header"><i class="material-icons">build</i>Serviços</div>
            <div class="collapsible-body"><span>Os serviços cadastrados aparecerão em uma seção específica do seu site. Você pode atualizar, deletar e recuperar registros deletados.</span></div>
        </li>
        <li>
            <div class="collapsible-header"><i class="material-icons">apps</i>Categorias</div>
            <div class="collapsible-body"><span>As categorias cadastradas podem ser atualizadas, deletadas e recuperadas. Uma categoria possui mais de um produto. Em uma seção espsecífica do seu site, seus produtos podem ser filtrados pelas categorias.</span></div>
        </li>
        <li>
            <div class="collapsible-header"><i class="material-icons">add_shopping_cart</i>Produtos</div>
            <div class="collapsible-body"><span>Os produtos cadastrados aparecerão em uma seção específica do seu site. Vocô pode atualizar, deletar e recuperar registros deletados. Um produto possui uma categoria. Os produtos são listados por categoria na seção "Categorias" deste painel.</span></div>
        </li>
        <li>
            <div class="collapsible-header"><i class="material-icons">group</i>Parceiros</div>
            <div class="collapsible-body"><span>Os parceiros cadastrados aparecerão em uma seção específica do seu site. Você pode atualizar, deletar e recuperar registros deletados.</span></div>
        </li>
        <li>
            <div class="collapsible-header"><i class="material-icons">place</i>Ver Site</div>
            <div class="collapsible-body"><span>Veja seu site!</span></div>
        </li>
    </ul>

    <a href="{{ route('dashboard') }}" class="btn blue">Voltar</a>
@endsection