routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'site', 'uses' => 'SiteController@index']);
Route::post('', ['as' => 'contact.send', 'uses' => 'SiteController@postContact']);

Route::get('/admin', 'Admin\AdminController@index')->name('dashboard');
Route::get('/admin/help', 'Admin\AdminController@help')->name('help');

Route::prefix('admin')->middleware('auth')->group(function () {
    Route::get('services/deleted', ['as' => 'services.deleted', 'uses' => 'Admin\ServiceController@deleted']);
    Route::put('services/{service}/recovery', ['as' => 'services.recovery', 'uses' => 'Admin\ServiceController@recovery']);
    Route::resource('services', 'Admin\ServiceController');

    Route::get('categories/{category}/products', ['as' => 'categories.products', 'uses' => 'Admin\CategoryController@showProducts']);
    Route::get('categories/deleted', ['as' => 'categories.deleted', 'uses' => 'Admin\CategoryController@deleted']);
    Route::put('categories/{category}/recovery', ['as' => 'categories.recovery', 'uses' => 'Admin\CategoryController@recovery']);
    Route::resource('categories', 'Admin\CategoryController');

    Route::get('products/deleted', ['as' => 'products.deleted', 'uses' => 'Admin\ProductController@deleted']);
    Route::put('products/{product}/recovery', ['as' => 'products.recovery', 'uses' => 'Admin\ProductController@recovery']);
    Route::resource('products', 'Admin\ProductController');

    Route::get('partners/deleted', ['as' => 'partners.deleted', 'uses' => 'Admin\PartnerController@deleted']);
    Route::put('partners/{partner}/recovery', ['as' => 'partners.recovery', 'uses' => 'Admin\PartnerController@recovery']);
    Route::resource('partners', 'Admin\PartnerController');
});

Route::post('/send', 'EmailController@send')->name('send');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name', 'deleted'
    ];

    public function products()
    {
        return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $request->user()->authorizeRole(['admin']);

        $categories = Category::where('deleted', '=', 'N')->orderBy('id', 'DESC')->paginate(5);
        $breadcrumbs = [
            ['url' => route('dashboard'), 'title' => 'Dashboard'],
            ['url' => '', 'title' => 'Categorias']
        ];

        return view('admin.categories.index', compact('categories', 'breadcrumbs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $request->user()->authorizeRole(['admin']);

        $breadcrumbs = [
            ['url' => route('dashboard'), 'title' => 'Dashboard'],
            ['url' => route('categories.index'), 'title' => 'Categorias'],
            ['url' => '', 'title' => 'Cadastrar']
        ];

        return view('admin.categories.create', compact('breadcrumbs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->user()->authorizeRole(['admin']);

        $this->validate($request, [
            'name' => 'required'
        ]);

        Category::create(['name' => $request->name]);

        return redirect()->route('categories.index')
            ->with('success', 'Categoria cadastrada com sucesso.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function showProducts(Request $request, $id)
    {
        $request->user()->authorizeRole(['admin']);

        $category = Category::find($id);
        $products = $category->products()->orderBy('id', 'DESC')->paginate(5);
        $breadcrumbs = [
            ['url' => route('dashboard'), 'title' => 'Dashboard'],
            ['url' => route('categories.index'), 'title' => 'Categorias'],
            ['url' => '', 'title' => $category->name]
        ];

        return view('admin.categories.products', compact('products', 'breadcrumbs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $request->user()->authorizeRole(['admin']);

        $category = Category::find($id);
        $breadcrumbs = [
            ['url' => route('dashboard'), 'title' => 'Dashboard'],
            ['url' => route('categories.index'), 'title' => 'Categorias'],
            ['url' => '', 'title' => 'Atualizar']
        ];

        return view('admin.categories.edit', compact('category', 'breadcrumbs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->user()->authorizeRole(['admin']);

        $this->validate($request, [
            'name' => 'required'
        ]);

        Category::find($id)->update($request->all());

        return redirect()->route('categories.index')
            ->with('success', 'Categoria atualizada com sucesso.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $request->user()->authorizeRole(['admin']);

        Category::find($id)->update(['deleted' => 'Y']);

        return redirect()->route('categories.index')
            ->with('success', 'Categoria deletada com sucesso.');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function deleted(Request $request)
    {
        $request->user()->authorizeRole(['admin']);

        $categories = Category::where('deleted', '=', 'Y')->orderby('id', 'DESC')->paginate(5);
        $breadcrumbs = [
            ['url' => route('dashboard'), 'title' => 'Dashboard'],
            ['url' => route('categories.index'), 'title' => 'Categorias'],
            ['url' => '', 'title' => 'Deletadas']
        ];

        return view('admin.categories.deleted', compact('categories', 'breadcrumbs'));
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function recovery(Request $request, $id)
    {
        $request->user()->authorizeRole(['admin']);

        Category::find($id)->update(['deleted' => 'N']);

        return redirect()->route('categories.index')
            ->with('success', 'Categoria recuperada com sucesso.');
    }
}

resources/views/admin/categories/_form.blade.php
<div class="input-field">
    <input id="name" name="name" type="text" class="validate">
    <label for="name">Nome</label>
</div>

resources/views/admin/categories/create.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('admin.components.breadcrumbs')

    @if(count($errors) > 0)
        <div class="row">
            <div class="col s12">
                <div class="card red darken-2">
                    <div class="card-content white-text">
                        <span class="card-title">Erros</span>
                        @foreach($errors->all() as $message)
                            <li>{{ $message }}</li>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <form action="{{ route('categories.store') }}" method="post">
            {{ csrf_field() }}

            @include('admin.categories._form')

            <a href="{{ route('categories.index') }}" class="btn red">Cancelar</a>
            <button class="btn green right">Cadastrar</button>
        </form>
    </div>
@endsection

resources/views/admin/categories/deleted.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('admin.components.breadcrumbs')

    @if(count($errors) > 0)
        <div class="row">
            <div class="col s12">
                <div class="card red darken-2">
                    <div class="card-content white-text">
                        <span class="card-title">Erros</span>
                        @foreach($errors->all() as $message)
                            <li>{{ $message }}</li>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <table>
            <thead>
                <td>#</td>
                <td>Nome</td>
                <td>Ação</td>
            </thead>
            <tbody>
                @foreach($categories as $category)
                    <tr>
                        <td>{{ $category->id }}</td>
                        <td>{{ $category->name }}</td>
                        <td>
                            <form action="{{ route('categories.recovery', $category->id) }}" method="post">
                                {{ method_field('PUT') }}
                                {{ csrf_field() }}

                                <button title="Recuperar" class="btn green">
                                    <i class="material-icons">restore</i>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="row">
        <a href="{{ route('categories.index') }}" class="btn blue left">Voltar</a>
    </div>

    <div align="center" class="row">
        {{ $categories->links() }}
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('admin.components.breadcrumbs')

    @if(count($errors) > 0)
        <div class="row">
            <div class="col s12">
                <div class="card red darken-2">
                    <div class="card-content white-text">
                        <span class="card-title">Erros</span>
                        @foreach($errors->all() as $message)
                            <li>{{ $message }}</li>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <form action="{{ route('categories.update', $category->id) }}" method="post">
            {{ method_field('PUT') }}
            {{ csrf_field() }}

            <div class="input-field">
                <input id="name" name="name" type="text" class="validate"
                    value="{{ isset($category->name) ? $category->name : '' }}">
                <label for="name">Nome</label>
            </div>

            <a href="{{ route('categories.index') }}" class="btn red">Cancelar</a>
            <button class="btn green right">Atualizar</button>
        </form>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('admin.components.breadcrumbs')

    @if(count($errors) > 0)
        <div class="row">
            <div class="col s12">
                <div class="card red darken-2">
                    <div class="card-content white-text">
                        <span class="card-title">Erros</span>
                        @foreach($errors->all() as $message)
                            <li>{{ $message }}</li>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <table>
            <thead>
                <td>#</td>
                <td>Nome</td>
                <!--<td>Ação</td>-->
            </thead>
            <tbody>
                @foreach($categories as $category)
                    <tr>
                        <td>{{ $category->id }}</td>
                        <td>{{ $category->name }}</td>
                        <td>
                            <form action="{{ route('categories.destroy', $category->id) }}" method="post">
                                <a title="Atualizar" href="{{ route('categories.edit', $category->id) }}" class="btn orange">
                                    <i class="material-icons">mode_edit</i>
                                </a>
                                <a title="Ver Produtos" href="{{ route('categories.products', $category->id) }}" class="btn blue">
                                    <i class="material-icons">visibility</i>
                                </a>

                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}

                                <button title="Deletar" class="btn red">
                                    <i class="material-icons">delete</i>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="row">
        <a href="{{ route('dashboard') }}" class="btn blue left">Voltar</a>
        <div class="right">
            <a href="{{ route('categories.create') }}" class="btn green">Cadastrar</a>
            <a href="{{ route('categories.deleted') }}" class="btn red">Deletadas</a>
        </div>
    </div>

    <div align="center" class="row">
        {{ $categories->links() }}
    </div>
@endsection

resources/views/admin/categories/products.blade.php
@extends('layouts.dashboard')

@section('content')
    @include('admin.components.breadcrumbs')

    @if(count($errors) > 0)
        <div class="row">
            <div class="col s12">
                <div class="card red darken-2">
                    <div class="card-content white-text">
                        <span class="card-title">Erros</span>
                        @foreach($errors->all() as $message)
                            <li>{{ $message }}</li>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <table>
            <thead>
                <td>#</td>
                <td>Nome</td>
                <td>Categoria</td>
                <td>Imagem</td>
                <td>Ação</td>
            </thead>
            <tbody>
                @foreach($products as $product)
                    <tr>
                        <td>{{ $product->id }}</td>
                        <td>{{ $product->name }}</td>
                        <td>{{ $product->category->name }}</td>
                        <td><img width="50" class="materialboxed" src="{{ $product->image->getUrl() }}"></td>
                        <td>
                            <form action="{{ route('products.destroy', $product->id) }}" method="post">
                                <a title="Atualizar" href="{{ route('products.edit', $product->id) }}" class="btn orange">
                                    <i class="material-icons">mode_edit</i>
                                </a>

                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}

                                <button title="Deletar" class="btn red">
                                    <i class="material-icons">delete</i>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="row">
        <a href="{{ route('categories.index') }}" class="btn blue left">Voltar</a>
    </div>

    <div align="center" class="row">
        {{ $products->links() }}
    </div>
@endsection